### ISSUE TITLE
pricing page needs clear "monthly"

### ISSUE THREAD

**Issue by gcoon151** [IBM-Bluemix-Docs/direct-link#131]
https://cloud.ibm.com/docs/infrastructure/direct-link?topic=direct-link-pricing-for-ibm-cloud-direct-link#pricing-for-ibm-cloud-direct-link?cm_sp=Cloud-Product-_-OnPageNavCTA-IBMCloudPlatform_IBMCloudInternetServices-_-DirectLink_SeePricing pricing page does not make clear anywhere if it's monthly or something else. I know it to be monthly but it needs to be made clear on the page.

**Comment by llundquist** [comment]
Thank you for your feedback. I am closing this issue to reopen it on our staging area.
